# $Id$
#
# This module contains the default settings for the RPKI portal gui.
#
# DO NOT EDIT!  This file is automatically generated from settings.py.in
# path to the myrpki command line tool

from django.conf import settings

# directory containing the resource handles served by the rpki portal gui
CONFDIR = settings.MYRPKI if hasattr(settings, 'CONFDIR') else '/usr/local/var/rpki/conf'

# maildir-style mailbox where uploaded requests are saved
INBOX = settings.MYRPKI if hasattr(settings, 'INBOX') else '/usr/local/var/rpki/inbox'

# maildir-style mailbox where responses to client requests are stored
OUTBOX = settings.MYRPKI if hasattr(settings, 'OUTBOX') else '/usr/local/var/rpki/outbox'

# uid the web server runs as
WEB_USER = settings.MYRPKI if hasattr(settings, 'WEB_USER') else ''

RPKI_CONF_TEMPLATE = settings.RPKI_CONF_TEMPLATE = settings.RPKI_CONF_TEMPLATE if hasattr(settings, 'RPKI_CONF_TEMPLATE') else '/usr/local/share/rpki/gui/rpki.conf.template'
